ALTER TABLE campaigns 
ADD COLUMN delay_seconds INTEGER DEFAULT 5,
ADD COLUMN batch_size INTEGER DEFAULT 30,
ADD COLUMN batch_delay_seconds INTEGER DEFAULT 60,
ADD COLUMN last_message_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN batch_counter INTEGER DEFAULT 0;
